*** Settings ***
#Resource     ../consolidato/cruscotto/contributor/AmmortizzamentoAzieneElaboration.resource
Resource     ../processi/consolidato/cruscotto/contributor/AmmortizzamentoAzieneElaboration.resource
Resource     ../processi/admin/AmmortizzamentoAzieneElaboration.resource
Resource    ../processi/consolidato/cruscotto/consolidator/AmmortamentoNodiElaboration.resource
Resource     ../processi/admin/AmmortamentoNodiElaboration.resource
Resource    ../processi/consolidato/cruscotto/consolidator/AnnullamentoRunner.resource
Resource     ../processi/admin/AnnullamentoRunner.resource
Resource    ../processi/consolidato/cruscotto/consolidator/CessImboInfragroup.resource
Resource     ../processi/admin/CessImboInfragroup.resource
Resource     ../processi/consolidato/cruscotto/contributor/Contrfinancial.resource
Resource     ../processi/admin/Contrfinancial.resource
Resource     ../processi/consolidato/cruscotto/contributor/DeconsolidamentoContributorUserToolsElaboration.resource
